### ISSUE TITLE
Compatibility with Sonarr V4 broken

### ISSUE THREAD

**Issue by Egrirt** [nickheyer/DiscoFlix#4]
Thanks for the bot, it's really useful! However I realized that it doesn't work with Sonarr v4, it spits the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/src/bot/discord_bot.py", line 439, in on_message
    await bound_fn()  # Resolves with fn / rejects with on_reject
    ^^^^^^^^^^^^^^^^
  File "/app/src/bot/discord_bot.py", line 235, in _find_content
    return await handler.process_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/bot/request_handler.py", line 240, in process_request
    self.results = self.get_content_list(self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/lib/sonarr_api.py", line 141, in lookup_series
    res = self.request_get(path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/lib/request_api.py", line 50, in request_get
    return res.json()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Hope you can fix it :)

**Comment by nickheyer** [comment]
Will start soon, thanks!
