### ISSUE TITLE
Error with first utilisation

### ISSUE THREAD

**Issue by Wazany** [nickheyer/DiscoFlix#6]
I use the latest docker and I get this error when I do "!df test"

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 4436, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/src/bot/discord_bot.py", line 437, in on_message
    handler = Message_Handler(message, MESSAGE_MAP, config())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/bot/message_handler.py", line 12, in __init__
    self.valid = self.__parse_message()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/bot/message_handler.py", line 20, in __parse_message
    or not self.__parse_permissions()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/bot/message_handler.py", line 57, in __parse_permissions
    return get_users_for_auth(self.server_id, permissions, self.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/bot/user_manager.py", line 50, in get_users_for_auth
    server = DiscordServer.get(server_id=server_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 6624, in get
    return sq.get()
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peewee.py", line 7075, in get
    raise self.model.DoesNotExist('%s instance matching query does '
models.models.DiscordServerDoesNotExist: <Model: DiscordServer> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."server_name", "t1"."server_id" FROM "discordserver" AS "t1" WHERE ("t1"."server_id" = ?) LIMIT ? OFFSET ?
Params: ['655831756498403334', 1, 0]`

**Comment by nickheyer** [comment]
@Wazany Would it be possible for you to send me your config?

If you click the "Config" button, then the down arrow next to "Save", then "Export", then click/select all three options ("Configuration", "Logs", "Users"), then "Export" - it will create a .json file which you could send to me via:

Email: nick@heyer.app
Discord: NicholasHeyer#4212

Feel free to remove any sensitive information from your configuration settings beforehand (like Tokens, urls, etc.)
